spring.config.activate.on-profile=test

# MySQL Database Configuration
#DRIVER_NAME=org.testcontainers.jdbc.ContainerDatabaseDriver
#DB_URL=jdbc:tc:mysql:8.0.36://off_coupon?TC_INITSCRIPT=file:src/main/resources/schema.sql
##DB_HOST=localhost
##DB_PORT=3306
##DB_DATABASE=off_coupon
#DB_USERNAME=root
#DB_PASSWORD=1234

DRIVER_NAME=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
DB_URL=jdbc:log4jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?serverTimezone=Asia/Seoul
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=off_coupon
DB_USERNAME=root
DB_PASSWORD=1234


# REDIS \uC124\uC815
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=redis1234

# RabbitMQ \uC124\uC815
RABBITMQ_HOST=127.0.0.1
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=admin
RABBITMQ_PASSWORD=admin123!@#