DROP TABLE IF EXISTS memeber;

CREATE TABLE memeber
(
    id IDENTITY PRIMARY KEY,
    email VARCHAR(40) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(40) NOT NULL,
    birthDate VARCHAR(40) NOT NULL,
    phone VARCHAR(40) NOT NULL
);