DROP TABLE IF EXISTS member;

CREATE TABLE member
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(40) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(40) NOT NULL,
    birthDate VARCHAR(40) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL
);
